# GitHub Pages configuration
title: "iBOL Europe BOLD curation datasets"
description: "Browse and download curated taxonomic database files for BOLD manual curation"

# Enable GitHub Pages
plugins:
  - jekyll-sitemap

# Include all files (including data directory)
include:
  - data
  - assets

# Exclude unnecessary files
exclude:
  - README.md
  - .gitignore
  - _instructions

# Set the base URL (will be automatically set by GitHub Pages)
baseurl: ""

# Theme (optional - using default)
# theme: minima