# GitHub Pages configuration
title: "BOLD Curation Database Browser"
description: "Browse and download database files for curation"

# Enable GitHub Pages
plugins:
  - jekyll-sitemap

# Include all files (including data directory)
include:
  - data

# Exclude unnecessary files
exclude:
  - README.md
  - .gitignore
  - dir_tree.md

# Set the base URL (will be automatically set by GitHub Pages)
baseurl: ""

# Theme (optional - using default)
# theme: minima
