name: Update File Structure

on:
  push:
    branches: [ main ]
    paths: 
      - 'data/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Generate file structure
      run: |
        cat > generate-structure.js << 'EOF'
        const fs = require('fs');
        const path = require('path');
        
        function getDirectoryStructure(dirPath, basePath = '') {
          const structure = {};
          
          try {
            const items = fs.readdirSync(dirPath);
            
            for (const item of items) {
              if (item.startsWith('.')) continue;
              
              const fullPath = path.join(dirPath, item);
              const relativePath = basePath ? `${basePath}/${item}` : item;
              const stats = fs.statSync(fullPath);
              
              if (stats.isDirectory()) {
                structure[item] = {
                  type: 'directory',
                  path: relativePath,
                  children: getDirectoryStructure(fullPath, relativePath)
                };
              } else {
                structure[item] = {
                  type: 'file',
                  path: relativePath,
                  size: stats.size,
                  modified: stats.mtime.toISOString()
                };
              }
            }
          } catch (error) {
            console.error(`Error reading directory ${dirPath}:`, error);
          }
          
          return structure;
        }
        
        const dataPath = './data';
        if (fs.existsSync(dataPath)) {
          const structure = getDirectoryStructure(dataPath);
          
          const output = `// Auto-generated file structure for iBOL Europe BOLD curation datasets
// Last updated: ${new Date().toISOString()}
// Repository: bge-barcoding/manual-curation

window.DATABASE_STRUCTURE = ${JSON.stringify(structure, null, 2)};
`;
          
          fs.writeFileSync('file-structure.js', output);
          console.log('File structure updated successfully');
          console.log(`Generated structure for ${Object.keys(structure).length} top-level taxonomic groups`);
        } else {
          console.log('Data directory not found');
          process.exit(1);
        }
        EOF
        
        node generate-structure.js
        
    - name: Commit updated structure
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add file-structure.js
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update file structure [skip ci]"
          git push
        fi
